### ISSUE TITLE
주특기 주차 LV2 과제 리뷰

### ISSUE THREAD

**Issue by sh-doveloper** [uiseongsang/nbc-spring-assignment-blog#1]
### CommentController 리뷰

1. HttpStatus.CREATED.value()를 사용하면 더 좋을것 같습니다.
https://github.com/uiseongsang/spring-lv2/blob/706f7f0d05d962bb61c40aa1ca876cfcd2d6463f/src/main/java/com/sparta/springlv2/controller/CommentController.java#L34

2. ResponseEntity 를 사용하신 점 잘하셨습니다.
ResponseBody와 차이점을 한번 찾아보시면 좋을것 같습니다.

3. status를 아래와 같이 작성하신 점 잘하셨습니다.
https://github.com/uiseongsang/spring-lv2/blob/706f7f0d05d962bb61c40aa1ca876cfcd2d6463f/src/main/java/com/sparta/springlv2/controller/CommentController.java#L41-L43

**Comment by sh-doveloper** [comment]
### CommentService 리뷰

1. orElseThrow() 이후 어떤 Exception을 Throw할것인지 명시해주는것이 좋을것 같습니다.
https://github.com/uiseongsang/spring-lv2/blob/706f7f0d05d962bb61c40aa1ca876cfcd2d6463f/src/main/java/com/sparta/springlv2/service/CommentService.java#L35

2. user를 객체로 비교하게되면 주소값을 비교하게 될것 같은데요. 혹시 테스트시 문제가 없었을까요? 객체에서 get을 통한 unique한 값을 비교하는것이 맞아보입니다.
https://github.com/uiseongsang/spring-lv2/blob/706f7f0d05d962bb61c40aa1ca876cfcd2d6463f/src/main/java/com/sparta/springlv2/service/CommentService.java#L38-L40

User Entity의 @EqualsAndHashCode 이것때문에 비교가 가능할수 있겠네요.

**Comment by sh-doveloper** [comment]
### Overview

- 전체적인 구성이나 코드의 간결성이 높습니다.
- 어노테이션이 기능들에 대한 이해도가 높습니다.
- 과제 구현을 잘 하신것 같습니다.

**Comment by uiseongsang** [comment]
코드리뷰 감사드립니다!
해당 피드백은 모두 반영을 한 뒤 lv4 진행을 하였습니다!!
